id: AEE4616A1
title: Prayer to Gyaltsen Tsemö Pung Gyen
type: translation
pechas:
- I18E7418F
- IF218121F
- I7507C57B
- I56F7D774
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:46.961329
  last_modified_at: 2023-01-04 12:45:46.961350
  collections:
  - Karma Chakme Series
  - Works of Tibetan Masters
alignment_to_base:
  I18E7418F/1C88: 81E3
  IF218121F/849F: 81E3
  I7507C57B/35EA: 81E3
  I56F7D774/C0F6: 81E3
